-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '94cb8136fe5b464d' HASH 'aa16db32061c3b6a53578c6af786665122fd4a26284c7344e73e9b97937d9923' ADMIN;         
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HT_ADMIN"(
    "ID" BIGINT NOT NULL
);              
ALTER TABLE "PUBLIC"."HT_ADMIN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HT_ADMIN;
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_ADMIN"(
    "IS_VERIFIED" BOOLEAN,
    "REGISTER_DATE" DATE,
    "USER_TYPE" TINYINT,
    "HTE_IDENTITY" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "ID" BIGINT,
    "LEVEL" BIGINT,
    "EMAIL" CHARACTER VARYING(255),
    "IMAGE_URL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."HTE_ADMIN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("HTE_IDENTITY");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_ADMIN;               
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HT_COMPANY"(
    "ID" BIGINT NOT NULL
);            
ALTER TABLE "PUBLIC"."HT_COMPANY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HT_COMPANY;              
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_COMPANY"(
    "IS_VERIFIED" BOOLEAN,
    "REGISTER_DATE" DATE,
    "USER_TYPE" TINYINT,
    "HTE_IDENTITY" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "ID" BIGINT,
    "LEVEL" BIGINT,
    "DESCRIPTION" CHARACTER VARYING(255),
    "EMAIL" CHARACTER VARYING(255),
    "IMAGE_URL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "STATUS" ENUM('ACCEPTED', 'PENDING', 'REJECTED')
);              
ALTER TABLE "PUBLIC"."HTE_COMPANY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("HTE_IDENTITY");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_COMPANY;             
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HT_STARTUP"(
    "ID" BIGINT NOT NULL
);            
ALTER TABLE "PUBLIC"."HT_STARTUP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HT_STARTUP;              
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_STARTUP"(
    "IS_VERIFIED" BOOLEAN,
    "REGISTER_DATE" DATE,
    "USER_TYPE" TINYINT,
    "HTE_IDENTITY" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "ID" BIGINT,
    "LEVEL" BIGINT,
    "DESCRIPTION" CHARACTER VARYING(255),
    "EMAIL" CHARACTER VARYING(255),
    "IMAGE_URL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "STATUS" ENUM('ACCEPTED', 'PENDING', 'REJECTED')
);              
ALTER TABLE "PUBLIC"."HTE_STARTUP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_45" PRIMARY KEY("HTE_IDENTITY");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_STARTUP;             
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HT_CLIENT"(
    "ID" BIGINT NOT NULL
);             
ALTER TABLE "PUBLIC"."HT_CLIENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E1" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HT_CLIENT;               
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_CLIENT"(
    "IS_VERIFIED" BOOLEAN,
    "REGISTER_DATE" DATE,
    "USER_TYPE" TINYINT,
    "HTE_IDENTITY" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "ID" BIGINT,
    "LEVEL" BIGINT,
    "EMAIL" CHARACTER VARYING(255),
    "IMAGE_URL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255)
); 
ALTER TABLE "PUBLIC"."HTE_CLIENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("HTE_IDENTITY");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_CLIENT;              
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HT_USER_BASE"(
    "ID" BIGINT NOT NULL
);          
ALTER TABLE "PUBLIC"."HT_USER_BASE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HT_USER_BASE;            
CREATE CACHED TABLE "PUBLIC"."ADMIN"(
    "ID" BIGINT NOT NULL
);           
ALTER TABLE "PUBLIC"."ADMIN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3B" PRIMARY KEY("ID");       
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.ADMIN;   
INSERT INTO "PUBLIC"."ADMIN" VALUES
(41),
(42),
(43),
(44),
(45);        
CREATE CACHED TABLE "PUBLIC"."CATEGORY"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) NOT NULL,
    "NAME" CHARACTER VARYING(255)
);     
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_31" PRIMARY KEY("ID");    
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORY;               
INSERT INTO "PUBLIC"."CATEGORY" VALUES
(1, 'Electronics & Technology'),
(2, 'Fashion & Accessories'),
(3, 'Beauty & Personal Care'),
(4, 'Home & Kitchen'),
(5, 'Grocery & Food'),
(6, 'Sports & Outdoors'),
(7, 'Toys & Games'),
(8, 'Health & Wellness'),
(9, 'Automotive & Accessories'),
(10, 'Tools & Home Improvement'),
(11, U&'Furniture & D\00e9cor'),
(12, 'Books & Stationery'),
(13, 'Pet Supplies'),
(14, 'Industrial & Office Supplies'),
(15, 'Baby & Kids'),
(16, 'Video Games'),
(17, 'Music, Movies & Entertainment');     
CREATE CACHED TABLE "PUBLIC"."CHALLENGE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) NOT NULL,
    "BENEFITS" CHARACTER VARYING(255) ARRAY,
    "BUDGET" NUMERIC(38, 2),
    "DESCRIPTION" CHARACTER VARYING(255),
    "END_DATE" DATE,
    "REQUIREMENTS" CHARACTER VARYING(255) ARRAY,
    "SHORT_DESCRIPTION" CHARACTER VARYING(255),
    "START_DATE" DATE,
    "TITLE" CHARACTER VARYING(255),
    "COMPANY_ID" BIGINT
); 
ALTER TABLE "PUBLIC"."CHALLENGE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");    
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.CHALLENGE;              
INSERT INTO "PUBLIC"."CHALLENGE" VALUES
(1, ARRAY ['Access to funding and mentorship from industry experts.', 'Opportunity to pilot and implement solutions in real-world scenarios.', 'Networking and collaboration with leaders in sustainability and innovation.'], 100000.00, 'How can we make factory production greener? Propose simple solutions to reduce waste and emissions.', DATE '2025-02-10', ARRAY ['Experience in sustainable technologies or environmental solutions.', 'Knowledge of innovative materials and energy-efficient systems.', 'Ability to design and prototype scalable eco-friendly solutions.'], 'Propose simple solutions to reduce waste and emissions in factory production.', DATE '2025-02-15', 'Eco-Friendly Manufacturing', 28),
(2, ARRAY ['Access to funding and mentorship from industry experts.', 'Opportunity to pilot and implement solutions in real-world scenarios.', 'Networking and collaboration with leaders in sustainability and innovation.'], 110000.00, 'Suggest innovative materials or processes that reduce the carbon footprint of construction.', DATE '2025-02-03', ARRAY ['Experience in sustainable technologies or environmental solutions.', 'Knowledge of innovative materials and energy-efficient systems.', 'Ability to design and prototype scalable eco-friendly solutions.'], 'Innovative materials or processes to reduce the carbon footprint of construction.', DATE '2025-02-15', 'Eco-Friendly Building Materials', 28),
(3, ARRAY [], 150000.00, 'Create an easy-to-deploy solar power kit for small businesses or homes in off-grid areas.', DATE '2025-02-13', ARRAY [], 'Easy-to-deploy solar power kit for off-grid areas.', DATE '2025-02-15', 'Powering Remote Areas', 29),
(4, ARRAY ['Access to funding and mentorship from industry experts.', 'Opportunity to pilot and implement solutions in real-world scenarios.', 'Networking and collaboration with leaders in sustainability and innovation.'], 140000.00, 'How can we make storing solar and wind energy more efficient and affordable? Share your ideas!', DATE '2025-02-15', ARRAY ['Experience in sustainable technologies or environmental solutions.', 'Knowledge of innovative materials and energy-efficient systems.', 'Ability to design and prototype scalable eco-friendly solutions.'], 'Efficient and affordable energy storage solutions.', DATE '2025-02-15', 'Smarter Energy Storage', 29),
(5, ARRAY [], 80000.00, 'How can we help cities or businesses use less water? Propose an affordable, easy-to-implement solution.', DATE '2025-02-18', ARRAY [], 'Affordable, easy-to-implement water-saving solutions.', DATE '2025-02-15', 'Water-Saving Tech', 30),
(6, ARRAY [], 130000.00, U&'Design a creative way to integrate solar panels into everyday life \2013 beyond rooftops!', DATE '2025-03-01', ARRAY [], 'Creative integration of solar panels into everyday life.', DATE '2025-02-15', 'A New Era of Solar Panels', 30),
(7, ARRAY [], 120000.00, 'Design a solution to help farmers cut down food waste, whether through better storage, distribution, or alternative uses.', DATE '2025-02-16', ARRAY [], 'Solutions to help farmers reduce food waste.', DATE '2025-02-15', 'Farming Without Waste', 31),
(8, ARRAY [], 115000.00, 'Can you develop an alternative to plastic that is cheap, scalable, and biodegradable?', DATE '2025-02-20', ARRAY [], 'Cheap, scalable, and biodegradable alternatives to plastic.', DATE '2025-02-15', 'Bye-Bye Plastic!', 31),
(9, ARRAY [], 90000.00, U&'What\2019s the next big idea in recycling? Think beyond traditional bins and propose something that makes waste separation fun and easy.', DATE '2025-02-24', ARRAY [], 'Innovative ideas for the future of recycling.', DATE '2025-02-15', 'The Future of Recycling', 32),
(10, ARRAY [], 105000.00, U&'What\2019s the next big idea in urban transportation? Help us make cities cleaner and more efficient.', DATE '2025-02-28', ARRAY [], 'Innovative ideas for urban transportation.', DATE '2025-02-15', 'Rethinking City Mobility', 32); 
CREATE CACHED TABLE "PUBLIC"."CHALLENGE_ODS"(
    "ID_STARTUP" BIGINT NOT NULL,
    "ID_ODS" BIGINT NOT NULL
);            
-- 14 +/- SELECT COUNT(*) FROM PUBLIC.CHALLENGE_ODS;          
INSERT INTO "PUBLIC"."CHALLENGE_ODS" VALUES
(1, 13),
(2, 9),
(2, 11),
(3, 7),
(3, 9),
(4, 7),
(4, 13),
(5, 6),
(6, 7),
(7, 2),
(7, 15),
(8, 12),
(9, 12),
(10, 11);             
CREATE CACHED TABLE "PUBLIC"."CLIENT"(
    "ID" BIGINT NOT NULL
);          
ALTER TABLE "PUBLIC"."CLIENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_76" PRIMARY KEY("ID");      
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.CLIENT;  
INSERT INTO "PUBLIC"."CLIENT" VALUES
(33),
(34),
(35),
(36),
(37),
(38),
(39),
(40);  
CREATE CACHED TABLE "PUBLIC"."CLIENT_MISSION"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "COMPLETED" BOOLEAN,
    "CLIENT_ID" BIGINT,
    "MISSION_ID" BIGINT
);      
ALTER TABLE "PUBLIC"."CLIENT_MISSION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4B" PRIMARY KEY("ID");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CLIENT_MISSION;          
CREATE CACHED TABLE "PUBLIC"."COMMENT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) NOT NULL,
    "COMMENT" CHARACTER VARYING(255),
    "POST_ID" BIGINT,
    "USER_ID" BIGINT
);     
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_63" PRIMARY KEY("ID");     
-- 25 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT;
INSERT INTO "PUBLIC"."COMMENT" VALUES
(1, 'I love VhAT: Revolutionizing industrial automation', 1, 1),
(2, 'I love GamingBuddy: Learning through play', 2, 1),
(3, U&'I love N\00f8rs: Enhancing personal health', 3, 1),
(4, 'I love AndLight: Affordable solar solutions', 4, 1),
(5, 'I love IM Hub: Supporting fair influencer marketing', 5, 1),
(6, 'I love Too Good To Go: Fighting hunger with rescued food', 6, 1),
(7, 'I love Doublepoint: Towards a zero-carbon future', 7, 1),
(8, 'I love BeCause: Building sustainable business networks', 8, 1),
(9, 'I love Bitlig Renewable Fuels: Clean energy for all', 9, 1),
(10, 'I love Mavi Bioscience: Protecting ecosystems', 10, 1),
(11, 'I love Doecos: Smart water heating solutions', 11, 1),
(12, 'I love VISCAN: Smart city planning', 12, 1),
(13, 'I love NXT Catch: Sustainable fishing gear', 13, 1),
(14, 'I love SquareRoot: Inclusive urban green spaces', 14, 1),
(15, 'I love Altered Power: Solar solutions for remote areas', 15, 1),
(16, 'I love Besen Group: Charging the future', 16, 1),
(17, 'I love Seacirc: Enabling circular economy', 17, 1),
(18, 'I love Manolin: Ensuring aquaculture health', 18, 1),
(19, 'I love Algaepro: Sustainable bioproducts', 19, 1),
(20, 'I love Elife: Eco-friendly urban mobility', 20, 1),
(21, 'I love Nordic Electrofuel: Pioneering synthetic fuels', 21, 1),
(22, 'I love Evoltec: Innovating for energy efficiency', 22, 1),
(23, 'I love EcoCharge: Solar-powered EV charging', 23, 1),
(24, 'I love WaterWise: Smart water management', 24, 1),
(25, 'I love GreenTransport: Electrifying public transit', 25, 1);   
CREATE CACHED TABLE "PUBLIC"."COMPANY"(
    "DESCRIPTION" CHARACTER VARYING(255),
    "STATUS" ENUM('ACCEPTED', 'PENDING', 'REJECTED'),
    "ID" BIGINT NOT NULL
);       
ALTER TABLE "PUBLIC"."COMPANY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_637" PRIMARY KEY("ID");    
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.COMPANY; 
INSERT INTO "PUBLIC"."COMPANY" VALUES
('Nuevaasdasdasdasd sdasdsa', 'ACCEPTED', 28),
('Startup specializing in renewable energy solutions, including high-efficiency solar panels and wind turbines.', 'ACCEPTED', 29),
('Leading company in the design and manufacturing of innovative solar panels using next-generation materials.', 'ACCEPTED', 30),
('Biotechnology company focused on creating bioplastics and biodegradable materials to reduce pollution.', 'ACCEPTED', 31),
('Initiative developing smart city solutions, including sustainable mobility and energy-efficient urban infrastructure.', 'ACCEPTED', 32);          
CREATE CACHED TABLE "PUBLIC"."LIKES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 608) NOT NULL,
    "POST_ID" BIGINT,
    "USER_ID" BIGINT
);             
ALTER TABLE "PUBLIC"."LIKES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_451" PRIMARY KEY("ID");      
-- 396 +/- SELECT COUNT(*) FROM PUBLIC.LIKES; 
INSERT INTO "PUBLIC"."LIKES" VALUES
(1, 1, 21),
(2, 2, 10),
(3, 3, 20),
(4, 4, 19),
(5, 5, 1),
(6, 6, 22),
(7, 7, 25),
(8, 8, 4),
(9, 9, 2),
(10, 10, 3),
(11, 11, 21),
(12, 12, 13),
(13, 13, 16),
(14, 14, 4),
(15, 15, 4),
(16, 16, 26),
(17, 17, 3),
(18, 18, 13),
(19, 19, 6),
(20, 20, 17),
(21, 21, 5),
(22, 22, 2),
(23, 23, 20),
(24, 24, 25),
(25, 25, 17),
(33, 1, 2),
(34, 2, 17),
(35, 3, 30),
(36, 4, 6),
(37, 5, 30),
(38, 6, 16),
(39, 7, 8),
(40, 8, 6),
(41, 9, 28),
(42, 10, 11),
(43, 11, 10),
(44, 12, 32),
(45, 13, 7),
(46, 14, 2),
(47, 15, 8),
(48, 16, 7),
(49, 17, 36),
(50, 18, 30),
(51, 19, 40),
(52, 20, 22),
(53, 21, 4),
(54, 22, 1),
(55, 23, 32),
(56, 24, 28),
(57, 25, 6),
(58, 1, 28),
(59, 2, 31),
(60, 3, 21),
(61, 4, 28),
(62, 5, 9),
(63, 6, 2),
(64, 7, 4),
(65, 8, 35),
(66, 9, 25),
(67, 11, 40),
(68, 12, 22),
(69, 13, 31),
(70, 14, 3),
(71, 15, 17),
(72, 17, 2),
(73, 18, 3),
(74, 19, 24),
(75, 20, 16),
(76, 21, 3),
(77, 22, 35),
(78, 23, 13),
(79, 24, 30),
(80, 25, 13),
(90, 2, 37),
(91, 3, 28),
(92, 4, 27),
(93, 5, 8),
(94, 6, 6),
(95, 7, 10),
(96, 9, 16),
(97, 10, 28),
(98, 11, 36),
(99, 13, 34),
(100, 14, 32),
(101, 15, 11),
(102, 16, 22),
(103, 17, 17),
(104, 18, 23),
(105, 19, 37),
(106, 20, 4),
(107, 21, 20),
(108, 22, 23),
(109, 24, 35),
(110, 25, 27),
(122, 1, 34),
(123, 3, 8),
(124, 4, 25),
(125, 5, 12),
(126, 6, 32),
(127, 7, 24),
(128, 8, 31),
(129, 9, 7),
(130, 10, 35),
(131, 11, 39),
(132, 14, 16),
(133, 15, 3),
(134, 16, 3),
(135, 17, 11),
(136, 19, 8),
(137, 21, 30),
(138, 22, 17),
(139, 24, 37),
(154, 1, 19),
(155, 2, 23),
(156, 3, 26),
(157, 5, 37),
(158, 6, 30),
(159, 8, 26),
(160, 9, 37),
(161, 10, 32),
(162, 11, 23),
(163, 12, 15),
(164, 13, 4),
(165, 14, 17),
(166, 15, 18),
(167, 16, 27),
(168, 17, 14),
(169, 18, 19),
(170, 19, 14),
(171, 20, 27),
(172, 22, 19),
(173, 23, 7),
(174, 24, 18),
(175, 25, 35),
(186, 1, 17),
(187, 2, 9),
(188, 3, 5),
(189, 4, 13),
(190, 6, 24),
(191, 7, 27),
(192, 8, 24),
(193, 9, 12),
(194, 11, 35),
(195, 12, 31),
(196, 14, 33),
(197, 15, 23),
(198, 16, 14),
(199, 17, 25),
(200, 18, 16),
(201, 21, 14),
(202, 22, 24),
(203, 23, 9),
(204, 24, 13),
(205, 25, 25),
(218, 1, 33),
(219, 2, 30),
(220, 3, 19),
(221, 4, 36),
(222, 6, 29),
(223, 7, 1),
(224, 8, 29),
(225, 10, 14),
(226, 11, 29),
(227, 12, 38),
(228, 13, 1),
(229, 14, 25),
(230, 15, 38),
(231, 16, 9),
(232, 19, 4),
(233, 20, 36),
(234, 21, 36),
(235, 22, 40),
(236, 23, 5),
(237, 25, 4),
(250, 1, 8),
(251, 2, 4),
(252, 3, 24),
(253, 4, 1),
(254, 5, 5),
(255, 6, 28),
(256, 7, 38),
(257, 9, 19),
(258, 10, 38),
(259, 11, 14),
(260, 12, 29),
(261, 13, 24),
(262, 15, 28),
(263, 16, 23),
(264, 17, 38),
(265, 18, 40),
(266, 19, 34),
(267, 20, 35),
(268, 21, 33),
(269, 22, 39),
(270, 24, 7),
(271, 25, 5),
(282, 1, 1),
(283, 2, 39),
(284, 3, 13),
(285, 4, 37),
(286, 5, 27),
(287, 7, 22),
(288, 9, 27),
(289, 10, 6),
(290, 11, 15),
(291, 13, 12),
(292, 14, 40),
(293, 15, 39),
(294, 16, 5),
(295, 18, 34),
(296, 20, 21),
(297, 21, 26),
(298, 22, 6),
(299, 24, 33),
(300, 25, 14),
(314, 1, 39),
(315, 2, 3),
(316, 3, 31),
(317, 4, 4),
(318, 5, 17),
(319, 6, 25),
(320, 7, 21),
(321, 8, 7),
(322, 9, 32),
(323, 10, 2),
(324, 11, 13),
(325, 12, 5),
(326, 13, 29),
(327, 14, 29),
(328, 15, 30),
(329, 17, 34),
(330, 18, 1),
(331, 20, 28),
(332, 21, 28),
(333, 25, 18),
(346, 1, 22),
(347, 2, 26),
(348, 3, 38),
(349, 4, 30),
(350, 5, 21),
(351, 6, 36),
(352, 7, 28),
(353, 8, 21),
(354, 9, 39),
(355, 10, 31),
(356, 11, 1),
(357, 14, 14),
(358, 15, 2),
(359, 16, 10),
(360, 17, 1),
(361, 18, 14),
(362, 19, 22),
(363, 21, 38),
(364, 22, 12),
(365, 23, 10),
(366, 24, 26),
(367, 25, 40),
(378, 1, 12),
(379, 2, 18),
(380, 3, 14),
(381, 4, 22),
(382, 5, 35),
(383, 6, 4),
(384, 8, 1),
(385, 9, 30),
(386, 10, 36),
(387, 11, 30),
(388, 12, 11),
(389, 13, 14),
(390, 14, 39),
(391, 16, 18),
(392, 19, 32),
(393, 20, 1),
(394, 21, 6),
(395, 22, 15),
(396, 23, 21),
(397, 24, 39),
(398, 25, 3),
(410, 1, 26),
(411, 2, 7),
(412, 3, 9),
(413, 5, 10),
(414, 7, 33),
(415, 8, 28),
(416, 11, 19),
(417, 13, 20),
(418, 14, 9),
(419, 15, 20),
(420, 16, 39),
(421, 17, 18);
INSERT INTO "PUBLIC"."LIKES" VALUES
(422, 18, 7),
(423, 19, 5),
(424, 20, 19),
(425, 21, 8),
(426, 22, 11),
(427, 24, 31),
(428, 25, 34),
(442, 1, 7),
(443, 2, 2),
(444, 3, 2),
(445, 4, 21),
(446, 5, 6),
(447, 6, 12),
(448, 7, 3),
(449, 8, 32),
(450, 9, 10),
(451, 11, 37),
(452, 12, 10),
(453, 13, 36),
(454, 14, 6),
(455, 16, 25),
(456, 18, 24),
(457, 19, 1),
(458, 20, 31),
(459, 21, 22),
(460, 22, 29),
(461, 23, 22),
(462, 24, 27),
(463, 25, 38),
(464, 1, 38),
(465, 3, 15),
(466, 4, 38),
(467, 5, 2),
(468, 8, 15),
(469, 9, 5),
(470, 10, 37),
(471, 16, 38),
(472, 18, 32),
(473, 20, 13),
(474, 22, 25),
(475, 23, 6),
(476, 24, 36),
(477, 25, 12),
(496, 2, 32),
(497, 3, 18),
(498, 5, 40),
(499, 6, 23),
(500, 8, 9),
(501, 9, 11),
(502, 10, 9),
(503, 11, 22),
(504, 12, 6),
(505, 13, 10),
(506, 15, 16),
(507, 17, 23),
(508, 18, 11),
(509, 20, 10),
(510, 21, 39),
(528, 1, 13),
(529, 2, 11),
(530, 5, 13),
(531, 7, 19),
(532, 8, 40),
(533, 11, 32),
(534, 12, 19),
(535, 16, 17),
(536, 17, 16),
(537, 18, 22),
(538, 19, 16),
(539, 21, 35),
(540, 22, 22),
(541, 23, 2),
(542, 25, 39),
(560, 1, 18),
(561, 4, 12),
(562, 5, 22),
(563, 7, 13),
(564, 8, 3),
(565, 10, 7),
(566, 11, 6),
(567, 12, 17),
(568, 15, 35),
(569, 16, 11),
(570, 17, 9),
(571, 18, 38),
(572, 19, 2),
(573, 21, 19),
(574, 22, 18),
(575, 24, 23),
(576, 25, 32),
(592, 1, 24),
(593, 2, 20),
(594, 3, 17),
(595, 4, 65),
(596, 6, 39),
(597, 11, 9),
(598, 12, 4),
(599, 13, 6),
(600, 16, 1),
(601, 17, 40),
(602, 18, 4),
(603, 19, 17),
(604, 20, 23),
(605, 22, 14),
(606, 24, 6),
(607, 25, 33);           
CREATE CACHED TABLE "PUBLIC"."MISSION"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "POINTS" INTEGER,
    "TYPE" ENUM('DAILY', 'WEEKLY')
);               
ALTER TABLE "PUBLIC"."MISSION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6A" PRIMARY KEY("ID");     
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.MISSION; 
INSERT INTO "PUBLIC"."MISSION" VALUES
(1, 'Help keep your local park clean by collecting litter and properly disposing of waste.', 'Park Cleanup Crew', 5, 'DAILY'),
(2, 'Join a tree-planting initiative and contribute to reforesting green areas in your city.', 'Tree Guardians', 10, 'WEEKLY'),
(3, 'Organize or participate in a local recycling campaign to encourage proper waste management.', 'Community Recycling Hero', 15, 'WEEKLY'),
(4, 'Ditch your car for a week! Walk, bike, or use public transport for short trips and reduce your carbon footprint.', 'Car-Free Challenge', 80, 'WEEKLY');           
CREATE CACHED TABLE "PUBLIC"."ODS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) NOT NULL,
    "IMAGE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);     
ALTER TABLE "PUBLIC"."ODS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");          
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.ODS;    
INSERT INTO "PUBLIC"."ODS" VALUES
(1, 'S-WEB-Goal-01.png', 'End of Poverty'),
(2, 'S-WEB-Goal-02.png', 'Zero Hunger'),
(3, 'S-WEB-Goal-03.png', 'Good Health and Well-being'),
(4, 'S-WEB-Goal-04.png', 'Quality Education'),
(5, 'S-WEB-Goal-05.png', 'Gender Equality'),
(6, 'S-WEB-Goal-06.png', 'Clean Water and Sanitation'),
(7, 'S-WEB-Goal-07.png', 'Affordable and Clean Energy'),
(8, 'S-WEB-Goal-08.png', 'Decent Work and Economic Growth'),
(9, 'S-WEB-Goal-09.png', 'Industry, Innovation, and Infrastructure'),
(10, 'S-WEB-Goal-10.png', 'Reduced Inequalities'),
(11, 'S-WEB-Goal-11.png', 'Sustainable Cities and Communities'),
(12, 'S-WEB-Goal-12.png', 'Responsible Consumption and Production'),
(13, 'S-WEB-Goal-13.png', 'Climate Action'),
(14, 'S-WEB-Goal-14.png', 'Life Below Water'),
(15, 'S-WEB-Goal-15.png', 'Life on Land'),
(16, 'S-WEB-Goal-16.png', 'Peace, Justice, and Strong Institutions'),
(17, 'S-WEB-Goal-17.png', 'Partnerships for the Goals');
CREATE CACHED TABLE "PUBLIC"."ORDER_LINE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "AMOUNT" INTEGER,
    "ORDER_ID" BIGINT,
    "PRODUCT_ID" BIGINT
);              
ALTER TABLE "PUBLIC"."ORDER_LINE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4BB" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_LINE;              
CREATE CACHED TABLE "PUBLIC"."ORDERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255),
    "PURCHASE_DATE" DATE,
    "SHIPPING_ADDRESS" CHARACTER VARYING(255),
    "SHIPPING_CITY" CHARACTER VARYING(255),
    "SHIPPING_COUNTRY" CHARACTER VARYING(255),
    "SHIPPING_PHONE" CHARACTER VARYING(255),
    "SHIPPING_ZIP_CODE" CHARACTER VARYING(255),
    "STATUS" TINYINT,
    "USER_ID" BIGINT
);   
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8B" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;  
CREATE CACHED TABLE "PUBLIC"."POST"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "IMAGE_URL" CHARACTER VARYING(255),
    "POST_DATE" DATE,
    "SHORT_DESCRIPTION" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255),
    "STARTUP_ID" BIGINT
);  
ALTER TABLE "PUBLIC"."POST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 25 +/- SELECT COUNT(*) FROM PUBLIC.POST;   
INSERT INTO "PUBLIC"."POST" VALUES
(1, 'Our AI-driven platform optimizes production processes, reducing waste and enhancing efficiency.', NULL, DATE '2025-02-15', 'Optimizing production with AI.', 'VhAT: Revolutionizing industrial automation', 1),
(2, 'We offer educational games that promote learning in a fun and engaging way for all ages.', NULL, DATE '2025-02-10', 'Making education fun for all ages.', 'GamingBuddy: Learning through play', 2),
(3, 'Our wearable technology tracks vital signs, encouraging healthier lifestyles.', NULL, DATE '2025-02-05', 'Wearable technology for better health.', U&'N\00f8rs: Enhancing personal health', 3),
(4, 'We develop solar-powered lighting systems to provide clean energy access.', NULL, DATE '2025-02-08', 'Providing clean energy through solar power.', 'AndLight: Affordable solar solutions', 4),
(5, 'We connect brands with ethical influencers to promote fair trade and ethical marketing practices.', NULL, DATE '2025-01-15', 'Connecting ethical influencers with brands.', 'IM Hub: Supporting fair influencer marketing', 5),
(6, 'We bridge the gap between surplus food and those in need, reducing food waste.', NULL, DATE '2025-02-15', 'Reducing food waste, feeding communities.', 'Too Good To Go: Fighting hunger with rescued food', 6),
(7, 'Our technology helps businesses track and reduce their carbon footprint effectively.', NULL, DATE '2025-02-12', 'Helping businesses track and cut emissions.', 'Doublepoint: Towards a zero-carbon future', 7),
(8, 'We enable companies to collaborate towards achieving global sustainability goals.', NULL, DATE '2025-02-07', 'Collaborating for a greener future.', 'BeCause: Building sustainable business networks', 8),
(9, 'We produce cost-effective renewable fuels to replace fossil energy sources.', NULL, DATE '2025-02-01', 'Affordable renewable fuel solutions.', 'Bitlig Renewable Fuels: Clean energy for all', 9),
(10, 'Our solutions reduce livestock emissions, preserving natural habitats and biodiversity.', NULL, DATE '2025-02-03', 'Reducing livestock emissions for sustainability.', 'Mavi Bioscience: Protecting ecosystems', 10),
(11, 'We develop water heating systems that minimize water and energy consumption.', NULL, DATE '2025-02-09', 'Efficient water and energy-saving systems.', 'Doecos: Smart water heating solutions', 11),
(12, 'Our technology supports sustainable urban development and reduces environmental impact.', NULL, DATE '2025-01-31', 'Technology for sustainable urban growth.', 'VISCAN: Smart city planning', 12),
(13, 'We design innovative fishing solutions that protect marine life and reduce bycatch.', NULL, DATE '2025-02-08', 'Protecting marine life with innovation.', 'NXT Catch: Sustainable fishing gear', 13),
(14, 'We bring green infrastructure to underserved communities, improving urban quality of life.', NULL, DATE '2025-01-26', 'Bringing greenery to underserved areas.', 'SquareRoot: Inclusive urban green spaces', 14),
(15, 'Our portable solar devices bring electricity to off-grid communities.', NULL, DATE '2025-01-25', 'Portable solar energy for off-grid regions.', 'Altered Power: Solar solutions for remote areas', 15),
(16, 'We install EV charging stations to promote clean mobility in urban areas.', NULL, DATE '2025-01-28', 'Expanding EV charging infrastructure.', 'Besen Group: Charging the future', 16),
(17, 'Our software helps companies transition to sustainable production models.', NULL, DATE '2025-01-18', 'Helping businesses adopt sustainable production.', 'Seacirc: Enabling circular economy', 17),
(18, 'We monitor aquatic animal health to ensure sustainable and healthy seafood production.', NULL, DATE '2025-02-06', 'Monitoring aquatic animal health.', 'Manolin: Ensuring aquaculture health', 18),
(19, 'We produce eco-friendly bioplastics from algae, reducing land and marine pollution.', NULL, DATE '2025-02-01', 'Eco-friendly bioplastics from algae.', 'Algaepro: Sustainable bioproducts', 19),
(20, 'We offer electric bikes as a sustainable transportation option for city dwellers.', NULL, DATE '2025-02-04', 'Electric bikes for greener cities.', 'Elife: Eco-friendly urban mobility', 20);            
INSERT INTO "PUBLIC"."POST" VALUES
(21, 'We transform renewable energy into sustainable fuel solutions.', NULL, DATE '2025-01-11', 'Renewable energy transformed into fuel.', 'Nordic Electrofuel: Pioneering synthetic fuels', 21),
(22, 'We provide advanced technologies to improve energy efficiency in industries.', NULL, DATE '2025-01-24', 'Advanced tech for industrial energy savings.', 'Evoltec: Innovating for energy efficiency', 22),
(23, 'We develop solar charging stations to make electric mobility greener.', NULL, DATE '2025-01-30', 'Making electric mobility even greener.', 'EcoCharge: Solar-powered EV charging', 23),
(24, 'Our technology helps optimize water use, ensuring access to clean water.', NULL, DATE '2025-01-27', 'Optimizing water usage efficiently.', 'WaterWise: Smart water management', 24),
(25, 'We offer electric public transport solutions to reduce emissions and improve air quality.', NULL, DATE '2025-01-04', 'Reducing emissions through electric transport.', 'GreenTransport: Electrifying public transit', 25);           
CREATE CACHED TABLE "PUBLIC"."POST_ODS"(
    "ID_POST" BIGINT NOT NULL,
    "ID_ODS" BIGINT NOT NULL
);    
-- 34 +/- SELECT COUNT(*) FROM PUBLIC.POST_ODS;               
INSERT INTO "PUBLIC"."POST_ODS" VALUES
(1, 9),
(1, 12),
(1, 13),
(2, 4),
(2, 10),
(3, 3),
(3, 9),
(4, 7),
(4, 13),
(5, 10),
(5, 9),
(6, 12),
(6, 13),
(6, 2),
(7, 13),
(7, 12),
(8, 9),
(9, 7),
(10, 15),
(11, 6),
(12, 11),
(13, 14),
(14, 11),
(15, 7),
(16, 11),
(17, 12),
(18, 3),
(19, 15),
(20, 11),
(21, 12),
(22, 9),
(23, 7),
(24, 6),
(25, 7);    
CREATE CACHED TABLE "PUBLIC"."PRODUCT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 65) NOT NULL,
    "CREATION_DATE" DATE,
    "DESCRIPTION" CHARACTER VARYING(255),
    "IMAGE_URL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PRICE" NUMERIC(38, 2),
    "STARTUP_ID" BIGINT
);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_18" PRIMARY KEY("ID");     
-- 48 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
INSERT INTO "PUBLIC"."PRODUCT" VALUES
(1, DATE '2025-02-15', 'Smart glasses for augmented reality', NULL, 'VhAT Smart Glasses', 499.99, 1),
(2, DATE '2025-02-15', 'Development kit for augmented reality', NULL, 'VhAT AR Kit', 299.99, 1),
(3, DATE '2025-02-15', 'Premium subscription for gamers', NULL, 'GamingBuddy Pro', 9.99, 2),
(4, DATE '2025-02-15', 'Ergonomic gaming controller', NULL, 'GamingBuddy Controller', 59.99, 2),
(5, DATE '2025-02-15', 'Smart wristband for health monitoring', NULL, U&'N\00f8rs Health Tracker', 129.99, 3),
(6, DATE '2025-02-15', 'Guided meditation application', NULL, U&'N\00f8rs Meditation App', 4.99, 3),
(7, DATE '2025-02-15', 'High-efficiency solar panel', NULL, 'AndLight Solar Panel', 199.99, 4),
(8, DATE '2025-02-15', 'Eco-friendly LED bulb', NULL, 'AndLight LED Bulb', 14.99, 4),
(9, DATE '2025-02-15', 'Analytics tool for influencers', NULL, 'IMHub Analytics', 49.99, 5),
(10, DATE '2025-02-15', 'Advertising campaign manager', NULL, 'IMHub Campaign Manager', 99.99, 5),
(11, DATE '2025-02-15', 'Rescued food box', NULL, 'Too Good To Go Box', 9.99, 6),
(12, DATE '2025-02-15', 'App to fight food waste', NULL, 'Too Good To Go App', 0.00, 6),
(13, DATE '2025-02-15', 'Smartwatch with integrated GPS', NULL, 'Doublepoint Smartwatch', 199.99, 7),
(14, DATE '2025-02-15', 'Device for tracking physical activity', NULL, 'Doublepoint Fitness Tracker', 79.99, 7),
(15, DATE '2025-02-15', 'Platform for monitoring corporate sustainability', NULL, 'BeCause Sustainability Dashboard', 99.99, 8),
(16, DATE '2025-02-15', 'Tool to track and reduce CO2 emissions', NULL, 'BeCause Carbon Tracker', 149.99, 8),
(17, DATE '2025-02-15', 'Sustainable fuel for industrial and domestic use', NULL, 'Bitlig BioFuel', 3.49, 9),
(18, DATE '2025-02-15', 'Kit to optimize fuel consumption and reduce waste', NULL, 'Bitlig Fuel Efficiency Kit', 89.99, 9),
(19, DATE '2025-02-15', 'Feed additive to cut livestock methane emissions by 80%', NULL, 'Mavi Methane Reducer', 59.99, 10),
(20, DATE '2025-02-15', 'Organic soil enrichment for sustainable farming', NULL, 'Mavi Soil Booster', 39.99, 10),
(21, DATE '2025-02-15', 'Smart heating system with renewable energy integration', NULL, 'Doecos Smart Heater', 299.99, 11),
(22, DATE '2025-02-15', 'Home insulation kit for energy efficiency', NULL, 'Doecos Insulation Kit', 89.99, 11),
(23, DATE '2025-02-15', 'Advanced 3D scanning for buildings and urban planning', NULL, 'VISCAN 3D Mapping System', 1499.99, 12),
(24, DATE '2025-02-15', 'AI-powered analysis of buildings'' energy efficiency', NULL, 'VISCAN Carbon Footprint Report', 199.99, 12),
(25, DATE '2025-02-15', 'Biodegradable fishing net to reduce ocean waste', NULL, 'NXT Sustainable Fishing Net', 299.99, 13),
(26, DATE '2025-02-15', 'IoT buoy for tracking sustainable fishing practices', NULL, 'NXT Smart Buoy', 399.99, 13),
(27, DATE '2025-02-15', 'Modular green roof system for urban areas', NULL, 'SquareRoot Green Roof Kit', 799.99, 14),
(28, DATE '2025-02-15', 'Automated irrigation system for sustainable cities', NULL, 'SquareRoot Smart Irrigation', 249.99, 14),
(29, DATE '2025-02-15', 'Portable solar charger for outdoor use', NULL, 'Altered Power Portable Solar Charger', 129.99, 15),
(30, DATE '2025-02-15', 'Compact solar panel for off-grid adventures', NULL, 'Altered Power Foldable Solar Panel', 199.99, 15),
(31, DATE '2025-02-15', 'Home electric vehicle charger', NULL, 'Besen EV Charger', 349.99, 16),
(32, DATE '2025-02-15', 'Fast-charging station for urban areas', NULL, 'Besen Public Charging Station', 7999.99, 16),
(33, DATE '2025-02-15', 'AI-based software for waste optimization', NULL, 'Seacirc Circular Economy Software', 399.99, 17),
(34, DATE '2025-02-15', 'Tool for monitoring sustainable supply chains', NULL, 'Seacirc Sustainable Supply Chain', 299.99, 17),
(35, DATE '2025-02-15', 'Aquaculture health monitoring platform', NULL, 'Manolin AquaHealth', 599.99, 18),
(36, DATE '2025-02-15', 'Water quality sensors for fish farms', NULL, 'Manolin Smart Sensors', 149.99, 18),
(37, DATE '2025-02-15', 'Biodegradable plastic made from algae', NULL, 'Algaepro BioPlastic', 49.99, 19);   
INSERT INTO "PUBLIC"."PRODUCT" VALUES
(38, DATE '2025-02-15', 'Sustainable algae-based protein supplement', NULL, 'Algaepro Protein Powder', 29.99, 19),
(39, DATE '2025-02-15', 'Eco-friendly electric bicycle', NULL, 'Elife Electric Bike', 1199.99, 20),
(40, DATE '2025-02-15', 'Long-lasting battery pack for e-bikes', NULL, 'Elife Smart Battery', 399.99, 20),
(41, DATE '2025-02-15', 'Synthetic fuel made from renewable energy', NULL, 'Nordic SynFuel', 5.99, 21),
(42, DATE '2025-02-15', 'Carbon capture and recycling unit', NULL, 'Nordic Carbon Capture System', 2499.99, 21),
(43, DATE '2025-02-15', 'AI-powered system to enhance energy efficiency in industrial facilities.', NULL, 'Evoltec Smart Grid Optimizer', 249.99, 22),
(44, DATE '2025-02-15', 'Solar-powered charging dock for EVs', NULL, 'EcoCharge Solar Charging Station', 4999.99, 23),
(45, DATE '2025-02-15', 'Smart sensor that detects water leaks in real-time to prevent waste and reduce costs.', NULL, 'WaterWise Leak Detector', 119.99, 24),
(46, DATE '2025-02-15', 'Affordable electric scooter for urban mobility', NULL, 'GreenTransport E-Scooter', 699.99, 25),
(47, DATE '2025-02-15', '100% biodegradable packaging', NULL, 'EcoPackaging Compostable Bag', 2.99, 26),
(48, DATE '2025-02-15', 'Shoes made from recycled plastics', NULL, 'SustainableFashion Recycled Sneakers', 89.99, 27);             
CREATE CACHED TABLE "PUBLIC"."PRODUCT_CATEGORY"(
    "ID_PRODUCT" BIGINT NOT NULL,
    "ID_CATEGORY" BIGINT NOT NULL
);    
-- 48 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_CATEGORY;       
INSERT INTO "PUBLIC"."PRODUCT_CATEGORY" VALUES
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),
(6, 1),
(7, 4),
(8, 4),
(9, 1),
(10, 1),
(11, 5),
(12, 5),
(13, 1),
(14, 1),
(15, 1),
(16, 1),
(17, 5),
(18, 5),
(19, 5),
(20, 5),
(21, 4),
(22, 4),
(23, 1),
(24, 1),
(25, 5),
(26, 5),
(27, 4),
(28, 4),
(29, 1),
(30, 1),
(31, 1),
(32, 1),
(33, 1),
(34, 1),
(35, 1),
(36, 1),
(37, 5),
(38, 5),
(39, 1),
(40, 1),
(41, 5),
(42, 5),
(43, 1),
(44, 1),
(45, 4),
(46, 1),
(47, 5),
(48, 2);         
CREATE CACHED TABLE "PUBLIC"."PROPOSAL"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 33) NOT NULL,
    "DATE" DATE,
    "DESCRIPTION" CHARACTER VARYING(255),
    "LINK" CHARACTER VARYING(255),
    "STATUS" TINYINT,
    "TITLE" CHARACTER VARYING(255),
    "CHALLENGE_ID" BIGINT,
    "STARTUP_ID" BIGINT
);      
ALTER TABLE "PUBLIC"."PROPOSAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F37" PRIMARY KEY("ID");   
-- 12 +/- SELECT COUNT(*) FROM PUBLIC.PROPOSAL;               
INSERT INTO "PUBLIC"."PROPOSAL" VALUES
(1, DATE '2025-01-15', 'Proposal to implement innovative filters in industrial smokestacks.', NULL, 1, NULL, 1, 1),
(2, DATE '2025-02-10', 'Development of portable solar panels for rural communities.', NULL, 0, NULL, 2, 2),
(3, DATE '2025-03-05', 'Technology for water purification in areas facing extreme drought.', NULL, 0, NULL, 3, 3),
(4, DATE '2025-03-20', 'Automated irrigation system that minimizes water waste.', NULL, 2, NULL, 4, 4),
(5, DATE '2025-04-01', 'Educational campaign about smart recycling in urban areas.', NULL, 1, NULL, 5, 5),
(6, DATE '2025-04-15', 'Route optimization to reduce transport emissions.', NULL, 2, NULL, 1, 6),
(7, DATE '2025-05-10', 'Drones to monitor crops and reduce pesticide usage.', NULL, 0, NULL, 4, 7),
(8, DATE '2025-06-01', 'Implementation of next-generation photovoltaic cells to boost solar efficiency by 25%.', NULL, 0, NULL, 6, 1),
(9, DATE '2025-06-10', 'A zero-waste farming model that converts organic residues into natural fertilizers.', NULL, 1, NULL, 7, 3),
(10, DATE '2025-07-01', 'A global campaign encouraging businesses and consumers to switch from single-use plastics to compostable alternatives.', NULL, 0, NULL, 8, 5),
(11, DATE '2025-07-15', 'An AI-driven sorting system designed to increase material recovery rates in urban recycling centers.', NULL, 2, NULL, 9, 6),
(12, DATE '2025-08-01', 'Development of a city-wide bike-sharing and carpooling platform powered by renewable energy sources.', NULL, 0, NULL, 10, 4);
CREATE CACHED TABLE "PUBLIC"."STARTUP"(
    "DESCRIPTION" CHARACTER VARYING(255),
    "STATUS" ENUM('ACCEPTED', 'PENDING', 'REJECTED'),
    "ID" BIGINT NOT NULL
);       
ALTER TABLE "PUBLIC"."STARTUP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B9" PRIMARY KEY("ID");     
-- 28 +/- SELECT COUNT(*) FROM PUBLIC.STARTUP;
INSERT INTO "PUBLIC"."STARTUP" VALUES
('Nuevaasdasdasdasd sdasdsa', 'ACCEPTED', 1),
('Educational app that uses video games to promote inclusive and accessible learning for everyone.', 'ACCEPTED', 2),
('Startup focused on developing wearable technology for health monitoring with a gender equity approach.', 'ACCEPTED', 3),
('Company developing sustainable lighting solutions with renewable energy technology and recyclable materials.', 'ACCEPTED', 4),
('Platform connecting brands with ethical influencers for responsible and sustainable marketing campaigns.', 'ACCEPTED', 5),
('App combating food waste by allowing users to buy surplus food at reduced prices.', 'ACCEPTED', 6),
('Technology company developing advanced sensors to optimize industrial processes with lower environmental impact.', 'ACCEPTED', 7),
('Sustainability management platform for companies, facilitating responsible decision-making.', 'ACCEPTED', 8),
('Developing technology to reduce sustainable fuel production costs.', 'ACCEPTED', 9),
('Innovative solution to reduce livestock methane emissions by 80%.', 'ACCEPTED', 10),
('Helping customers adopt more sustainable heating sources at home.', 'ACCEPTED', 11),
('3D capture of buildings to improve efficiency and reduce carbon footprint.', 'ACCEPTED', 12),
('Innovations for sustainable fishing and waste reduction in fishing equipment.', 'ACCEPTED', 13),
('Platform to promote green infrastructure in cities.', 'ACCEPTED', 14),
('Portable renewable energy for outdoor enthusiasts.', 'ACCEPTED', 15),
('Distribution of electric chargers for sustainable mobility.', 'ACCEPTED', 16),
('Software to improve business sustainability through data usage.', 'ACCEPTED', 17),
('Digital health management for sustainable aquaculture.', 'ACCEPTED', 18),
('Production of biomass from microalgae for bioplastics and food.', 'ACCEPTED', 19),
('Manufacturing and distribution of electric bicycles.', 'ACCEPTED', 20),
('Transforming electric energy into renewable fuels.', 'ACCEPTED', 21),
('Technology services and products for the sustainable energy industry.', 'ACCEPTED', 22),
('Solar charging stations for electric vehicles.', 'ACCEPTED', 23),
('Monitoring technology for efficient water use.', 'ACCEPTED', 24),
('Electric and shared public transportation solutions.', 'ACCEPTED', 25),
('Development of biodegradable and compostable packaging.', 'ACCEPTED', 26),
('Sustainable fashion with recycled materials and fair trade.', 'ACCEPTED', 27),
(NULL, 'ACCEPTED', 65); 
CREATE CACHED TABLE "PUBLIC"."STARTUP_ODS"(
    "ID_STARTUP" BIGINT NOT NULL,
    "ID_ODS" BIGINT NOT NULL
);              
-- 63 +/- SELECT COUNT(*) FROM PUBLIC.STARTUP_ODS;            
INSERT INTO "PUBLIC"."STARTUP_ODS" VALUES
(2, 4),
(2, 10),
(2, 8),
(3, 3),
(3, 5),
(3, 10),
(4, 12),
(4, 9),
(4, 13),
(5, 8),
(5, 10),
(5, 17),
(6, 2),
(6, 12),
(6, 13),
(7, 9),
(7, 12),
(7, 8),
(8, 9),
(8, 12),
(9, 13),
(9, 7),
(10, 13),
(10, 12),
(11, 7),
(11, 11),
(12, 9),
(12, 11),
(13, 14),
(13, 12),
(14, 11),
(14, 13),
(15, 7),
(15, 13),
(16, 7),
(16, 11),
(17, 12),
(17, 9),
(18, 14),
(18, 9),
(19, 12),
(19, 13),
(20, 11),
(20, 7),
(21, 13),
(21, 7),
(22, 9),
(22, 13),
(23, 7),
(23, 11),
(24, 6),
(24, 13),
(25, 11),
(25, 13),
(26, 12),
(26, 13),
(27, 12),
(27, 8),
(1, 1),
(1, 2),
(1, 3),
(65, 1),
(65, 2);     
CREATE CACHED TABLE "PUBLIC"."USER_PREFERENCES"(
    "ID_USER" BIGINT NOT NULL,
    "ID_ODS" BIGINT NOT NULL
);            
-- 16 +/- SELECT COUNT(*) FROM PUBLIC.USER_PREFERENCES;       
INSERT INTO "PUBLIC"."USER_PREFERENCES" VALUES
(33, 7),
(33, 6),
(34, 7),
(34, 13),
(35, 9),
(35, 8),
(36, 5),
(36, 4),
(37, 9),
(37, 16),
(38, 11),
(38, 2),
(39, 3),
(39, 6),
(40, 12),
(40, 15);           
CREATE CACHED TABLE "PUBLIC"."USER_BASE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 97) NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "IMAGE_URL" CHARACTER VARYING(255),
    "IS_VERIFIED" BOOLEAN NOT NULL,
    "LEVEL" BIGINT,
    "NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "REGISTER_DATE" DATE,
    "USER_TYPE" TINYINT
);               
ALTER TABLE "PUBLIC"."USER_BASE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BC0" PRIMARY KEY("ID");  
-- 46 +/- SELECT COUNT(*) FROM PUBLIC.USER_BASE;              
INSERT INTO "PUBLIC"."USER_BASE" VALUES
(1, 'contact@vhat.com', 'hy0vi7569zs61_05be1c148e5747dc8de7232c57c518ad.png', TRUE, 0, 'VhAT', '$2a$10$cfjehMN9ivB05AfC0AtKYusLuOZ/9Z46oF4r8ZINSEvxw0pekGEGm', NULL, 2),
(2, 'info@gamingbuddy.com', NULL, TRUE, 0, 'GamingBuddy', '$2a$10$zPFNA41yeIXClD9Bw6cwcO96QcLBQL7ZoG86MtodExhevIsC2BuBW', NULL, 2),
(3, 'hello@nors.com', NULL, TRUE, 0, U&'N\00f8rs', '$2a$10$2ACdlx59/GOnfvxWtpleSeTCvqqkFrjQg9yxsRkCKQQEGsCc1L9Oa', NULL, 2),
(4, 'contact@andlight.com', NULL, TRUE, 0, 'AndLight', '$2a$10$q.TmY.wdILQWJ3EdRCE1runfVfRofLB8O.Mq5DEkDbxaGZJ/1c/4O', NULL, 2),
(5, 'info@imhub.com', NULL, TRUE, 0, 'Influencer Marketing Hub', '$2a$10$Dppm9GVNQfSQct3KoSiH8u6VD/IB02cjbfTY6rrRDg0u7Md4gEuZa', NULL, 2),
(6, 'contact@toogoodtogo.com', NULL, TRUE, 0, 'Too Good To Go', '$2a$10$LthZUo1YXE6zwejqn35IZu3VdAx3qXsoc3WKOOTZveRnZsXA441Gm', NULL, 2),
(7, 'info@doublepoint.com', NULL, TRUE, 0, 'Doublepoint', '$2a$10$DLXIO.o46QvACvZe72QjTOd6DoQoyLCmThEvy2QJIjJbX0q74ZOZC', NULL, 2),
(8, 'contact@because.com', NULL, TRUE, 0, 'BeCause', '$2a$10$UfDwYJhe.lfcqwxk3aXNwu4VxQP8.wAMFmqMul8iGIXvXknKdyu3i', NULL, 2),
(9, 'info@bitligrenewables.com', NULL, TRUE, 0, 'Bitlig Renewable Fuels', '$2a$10$zK9/F2XOOYcClnNmNZF2ce5XH3r4zqqz.yCLITVZFLhE.v8PVF6hK', NULL, 2),
(10, 'contact@mavibioscience.com', NULL, TRUE, 0, 'Mavi Bioscience', '$2a$10$E.erXTJXHMps0uo2hLHt8uvLgwMPafT28fufbkZHtu/3kTG8QVtrS', NULL, 2),
(11, 'info@doecos.com', NULL, TRUE, 0, 'Doecos', '$2a$10$yYKC6bAK53yA16cpvucYPeNedwp2ypIuJ3TUXjNmmekdKzzlLBb0K', NULL, 2),
(12, 'contact@viscan.com', NULL, TRUE, 0, 'VISCAN', '$2a$10$gzeG9ucqPb/rg1M/MNbfSut0pjJCOwkI.kVV2RhVX.qUNtO.cDTPy', NULL, 2),
(13, 'info@nxtcatch.com', NULL, TRUE, 0, 'NXT Catch AS', '$2a$10$I/jURUFJEsyxuevCyXpjLu7io6r5BYqFhyQMzgRFf6otgzOU0drOW', NULL, 2),
(14, 'contact@squareroot.com', NULL, TRUE, 0, 'SquareRoot', '$2a$10$zswa2gVJZEDvXSyS4AGNF.LgFUx1q3SVavkd2Jz3m8GNq/mFaPQfK', NULL, 2),
(15, 'info@alteredpower.com', NULL, TRUE, 0, 'Altered Power AS', '$2a$10$F5FlYTwPTs5GKHIljuTK0u9uGYWjh80pSocp6xwE54iXICO2L5bO6', NULL, 2),
(16, 'contact@besengroup.com', NULL, TRUE, 0, 'Besen Group AS', '$2a$10$IPYfpXJ.GfFKd.3UNFNyK.KpPFiS9FOCNjxToZELCiSYpXYvRFotK', NULL, 2),
(17, 'info@seacirc.com', NULL, TRUE, 0, 'Seacirc', '$2a$10$z7Er1V8CkpxjP/DkTsvNne4ejoTouUJ6v188crxWa1R1ATQ.lxNgC', NULL, 2),
(18, 'contact@manolin.com', NULL, TRUE, 0, 'Manolin', '$2a$10$z10wLSIhNa02FHiaUmWyh.wJT6GB.X8b7rhOc2OSVAxYdGjalv3RK', NULL, 2),
(19, 'info@algaepro.com', NULL, TRUE, 0, 'Algaepro AS', '$2a$10$6z9sIqrIvLms0OJKMdUjS.odvNXlEYfF4DrhOvlkKLXx7k6.rWvO6', NULL, 2),
(20, 'contact@elife.com', NULL, TRUE, 0, 'Elife AS', '$2a$10$WbiTs3BXp3eVIR9vW8hvqOoDqy2YSHYqBmcnAia6Om1pko2utVTMa', NULL, 2),
(21, 'info@nordicelectrofuel.com', NULL, TRUE, 0, 'Nordic Electrofuel', '$2a$10$qGt9hK/wyryFgdK29QWc7ut6MimvmGome0DK7glfQpE9orl4rt3wm', NULL, 2),
(22, 'contact@evoltec.com', NULL, TRUE, 0, 'Evoltec', '$2a$10$nPw8aKFdId0CLLci3lZ8g.awBVovNSOfDn7TMjn7ss5X80sLL3SRO', NULL, 2),
(23, 'info@ecocharge.com', NULL, TRUE, 0, 'EcoCharge', '$2a$10$JDZG.CCbdgEXyzq0PzrSnuwHiCdreZRqtRZrpb.l3CmXch6MeYhQu', NULL, 2),
(24, 'contact@waterwise.com', NULL, TRUE, 0, 'WaterWise', '$2a$10$QGoOqybUhWmJ4evrGDQJaO0Idm1LyK2yddc5vQK1lE/WogWvBnV6K', NULL, 2),
(25, 'info@greentransport.com', NULL, TRUE, 0, 'GreenTransport', '$2a$10$bvFnlgdf.9CtKF.VNRdWge7kcjXfVNDMFTNzBAoag36ERxo.x0OkG', NULL, 2),
(26, 'contact@ecopackaging.com', NULL, TRUE, 0, 'EcoPackaging', '$2a$10$hy7bB/yrRazfu.HPhuaK9.3K4r4sxsiW7Rg3gEnjtzIT3UbobBKoe', NULL, 2),
(27, 'info@sustainablefashion.com', NULL, TRUE, 0, 'SustainableFashion', '$2a$10$zejx/qQudXwAC8dXRhGCiudTJR1bKURVFALCgPC89T7nfWVNRdDZG', NULL, 2),
(28, 'eco@vision.com', 'hy0vi7569zs61_be389dfa61074e41ae6aa5b099f64d44.png', TRUE, 1, 'EcoVision', '$2a$10$6ti5IJxWo.pPMuZyja15ouRbsg5EC9MYPKJI1svrOG9iiid8yK3E6', NULL, 1),
(29, 'contact@greenhorizon.com', NULL, TRUE, 2, 'GreenHorizon', '$2a$10$ppTkNkqcIMNqGAh67VT5tOY28W.YwbHAZE9/EqRptN5pQni6XbCR6', NULL, 1),
(30, 'info@solarpioneer.com', NULL, TRUE, 3, 'SolarPioneer', '$2a$10$xgwMaxRd8mT8r/Vh4R1AEevQUZanQLR0QKax6VzG3yUNN1IQ7ZV0K', NULL, 1); 
INSERT INTO "PUBLIC"."USER_BASE" VALUES
(31, 'support@biocraft.com', NULL, TRUE, 2, 'BioCraft', '$2a$10$gaiibuUlmusvIhTnbq9PDOG9GOmw9sSM8LlWHw/AGEZ2ZFOvbXP5m', NULL, 1),
(32, 'urban@flow.com', NULL, TRUE, 1, 'UrbanFlow', '$2a$10$pfjjpc8IPC0SKN5bERcLbOEVgkYpFEyY2e.Gtvc1G48ITJXk7sLxK', NULL, 1),
(33, 'alice@example.com', NULL, TRUE, 0, 'Alice Johnson', '$2a$10$scl2qJYa3z5iCJf.rVDFp.MZQS9cI5y3YZ0mn6QXwc9ayfc4eT47q', NULL, 0),
(34, 'bob@example.com', NULL, TRUE, 0, 'Bob Smith', '$2a$10$ze9hMNFdj.4vsSSRNmeyu.2QoVMzeQg8AD6bYYIBALqjvaIP28bFC', NULL, 0),
(35, 'charlie@example.com', NULL, TRUE, 0, 'Charlie Brown', '$2a$10$8gkptG2DdqTTbwZwvfzc1.t9wiALlOjhxKQ/u54WZCGDSmL3xJ9TS', NULL, 0),
(36, 'diana@example.com', NULL, TRUE, 0, 'Diana Prince', '$2a$10$8/KFZaSFOZ/sbUBJQf9LeuwsRGtSzJ6ecUNubQkwJOQS75JMVmRXW', NULL, 0),
(37, 'ethan@example.com', NULL, TRUE, 0, 'Ethan Hunt', '$2a$10$n24rhdnipWSNUrZCJqVgtOsAHKgxJ3DRZl1uc3HWLmiemg3rTw/zK', NULL, 0),
(38, 'fiona@example.com', NULL, TRUE, 0, 'Fiona Gallagher', '$2a$10$aMLg6N4.IOGDtx/1x7yt/uTESU1rvQIG9.KlgmJZO1nQvWQdwWbAi', NULL, 0),
(39, 'george@example.com', NULL, TRUE, 0, 'George Miller', '$2a$10$2NUkVxjzXx.2juuItRS7aORu4GtcIdivBD6Bb/DIjuilzkDI4fbcG', NULL, 0),
(40, 'hannah@example.com', NULL, TRUE, 0, 'Hannah Baker', '$2a$10$ADVbJvnCMwlwfdhkFLWDQeg8l8zDtYuyfhWEcp03ijhqx5X5PgZEa', NULL, 0),
(41, 'daniel@admin.com', NULL, TRUE, 0, 'Daniel', '$2a$10$aQD03NI4ccgMpvkdJgy1w.pvBaeAfXfIKE6y61SJjB6xryJ12Zt/G', NULL, 3),
(42, 'aaron@admin.com', NULL, TRUE, 0, 'Aaron', '$2a$10$zOpSqgQgvHKXRpW3.sMHYOkVnPCQR5mhGv9xBa4cPkR6gN2BgO/tS', NULL, 3),
(43, 'cristian@admin.com', NULL, TRUE, 0, 'Cristian', '$2a$10$4OoTyBEcD85bKtcs2bT6zujHwBPGfy3Y4bZmRmVQcgWLXnquji7tO', NULL, 3),
(44, 'lorenzo@admin.com', NULL, TRUE, 0, 'Lorenzo', '$2a$10$.lGlqWhXHohhzPsxr0Kl7uJRaAYGQmxqIU4GmjN35gfSpVDUmo.Ru', NULL, 3),
(45, 'carlos@admin.com', NULL, TRUE, 0, 'Carlos', '$2a$10$WKqhPYYbN2JojHbjxISZ9e4mdecDvFxKrQslak3BnYWKK9P8puUeu', NULL, 3),
(65, 'aaron.carrera@iesdoctorbalmis.com', 'Neon_Artwork_Full_605027264b0f4b6480e9f0e6d8fb19b9.png', TRUE, 0, 'John Doae', '$2a$10$vx15L3XhS71tlUNOPkq1cOHjxZ48kpOCEOnWzPxIPGlhtxqXRrEde', DATE '2025-02-16', 2);            
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" CHECK("STATUS" BETWEEN 0 AND 6) NOCHECK; 
ALTER TABLE "PUBLIC"."USER_BASE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BC" CHECK("USER_TYPE" BETWEEN 0 AND 3) NOCHECK;          
ALTER TABLE "PUBLIC"."PROPOSAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F3" CHECK("STATUS" BETWEEN 0 AND 2) NOCHECK;              
ALTER TABLE "PUBLIC"."USER_BASE" ADD CONSTRAINT "PUBLIC"."UK17G9KHVRJBXKAE551JJ8BAEM2" UNIQUE NULLS DISTINCT ("EMAIL");       
ALTER TABLE "PUBLIC"."USER_BASE" ADD CONSTRAINT "PUBLIC"."UK1ITY61R68H9FIFSP294GDJE1H" UNIQUE NULLS DISTINCT ("NAME");        
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FKR4215BA2PPKHOW8KBKE9SXJ0S" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER_BASE"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."LIKES" ADD CONSTRAINT "PUBLIC"."FKOWD6F4S7X9F3W50PVLO6X3B41" FOREIGN KEY("POST_ID") REFERENCES "PUBLIC"."POST"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."PROPOSAL" ADD CONSTRAINT "PUBLIC"."FK30YIUSA4SD67N0WFPMTK2KNQB" FOREIGN KEY("STARTUP_ID") REFERENCES "PUBLIC"."STARTUP"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."CLIENT" ADD CONSTRAINT "PUBLIC"."FKQY6L66D4EFQRVS81XTLACEK2K" FOREIGN KEY("ID") REFERENCES "PUBLIC"."USER_BASE"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."USER_PREFERENCES" ADD CONSTRAINT "PUBLIC"."FKFHEXD51DJL8XH6EMP1F71EQ5W" FOREIGN KEY("ID_USER") REFERENCES "PUBLIC"."CLIENT"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."CHALLENGE_ODS" ADD CONSTRAINT "PUBLIC"."FKT9IU1XSFH0X16EM9TYUHW2YFV" FOREIGN KEY("ID_STARTUP") REFERENCES "PUBLIC"."CHALLENGE"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."STARTUP" ADD CONSTRAINT "PUBLIC"."FK1JSKPDWQE628AF95NB50NB8KD" FOREIGN KEY("ID") REFERENCES "PUBLIC"."USER_BASE"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."LIKES" ADD CONSTRAINT "PUBLIC"."FKKHCWYGAPQB67Y23GFR5RQD8OG" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER_BASE"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."FK68LIMXX1XHATPPWREIYXEVG4N" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER_BASE"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."ORDER_LINE" ADD CONSTRAINT "PUBLIC"."FKPF904TCI8GARYPKVM32CQUPYE" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."POST_ODS" ADD CONSTRAINT "PUBLIC"."FKMDBVYEU70NUM4M81SLUGQYNFJ" FOREIGN KEY("ID_ODS") REFERENCES "PUBLIC"."ODS"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."CLIENT_MISSION" ADD CONSTRAINT "PUBLIC"."FKQ2B9E66UEA5IRY1GAGNBE3XU7" FOREIGN KEY("MISSION_ID") REFERENCES "PUBLIC"."MISSION"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."POST" ADD CONSTRAINT "PUBLIC"."FKKC9U4PL26A02383A44J5N3EFO" FOREIGN KEY("STARTUP_ID") REFERENCES "PUBLIC"."STARTUP"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."PRODUCT_CATEGORY" ADD CONSTRAINT "PUBLIC"."FKT4SN9FS5JU7D8MCOPORLYHFUN" FOREIGN KEY("ID_PRODUCT") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."PRODUCT_CATEGORY" ADD CONSTRAINT "PUBLIC"."FK4Y2UCYMPLQXYCF58MYN6ABCV2" FOREIGN KEY("ID_CATEGORY") REFERENCES "PUBLIC"."CATEGORY"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."PROPOSAL" ADD CONSTRAINT "PUBLIC"."FK157Q3UQOFKTBQ7XYUESJNP8DF" FOREIGN KEY("CHALLENGE_ID") REFERENCES "PUBLIC"."CHALLENGE"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."STARTUP_ODS" ADD CONSTRAINT "PUBLIC"."FKP8HUYX7RN16GH86NLSYJPP85I" FOREIGN KEY("ID_ODS") REFERENCES "PUBLIC"."ODS"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."FK22JML460DX0SY3V480N3SAHTC" FOREIGN KEY("STARTUP_ID") REFERENCES "PUBLIC"."STARTUP"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."STARTUP_ODS" ADD CONSTRAINT "PUBLIC"."FKEAM7OUFUT6GFBUH5AV5GI08U5" FOREIGN KEY("ID_STARTUP") REFERENCES "PUBLIC"."STARTUP"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."COMPANY" ADD CONSTRAINT "PUBLIC"."FK9NAQTWW1ORRVQM3R0ADO9NYOG" FOREIGN KEY("ID") REFERENCES "PUBLIC"."USER_BASE"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."USER_PREFERENCES" ADD CONSTRAINT "PUBLIC"."FK89NL75S3YVFNK5F98A87DMWC4" FOREIGN KEY("ID_ODS") REFERENCES "PUBLIC"."ODS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."POST_ODS" ADD CONSTRAINT "PUBLIC"."FKTMC45N0EUXK6M128TO9A5S8V5" FOREIGN KEY("ID_POST") REFERENCES "PUBLIC"."POST"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."CHALLENGE_ODS" ADD CONSTRAINT "PUBLIC"."FK81DSEF7YUB7KL4SA5SGXW6IG8" FOREIGN KEY("ID_ODS") REFERENCES "PUBLIC"."ODS"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."ADMIN" ADD CONSTRAINT "PUBLIC"."FKNC6XF5I3FO4WX07S4DFF8GYQR" FOREIGN KEY("ID") REFERENCES "PUBLIC"."USER_BASE"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."FKS1SLVNKUEMJSQ2KJ4H3VHX7I1" FOREIGN KEY("POST_ID") REFERENCES "PUBLIC"."POST"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."ORDER_LINE" ADD CONSTRAINT "PUBLIC"."FKK9F9T1TMKBQ5W27U8RRJBXXG6" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."ORDERS"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."CHALLENGE" ADD CONSTRAINT "PUBLIC"."FK6P7DCOSPG33FOHC66Y1P9A020" FOREIGN KEY("COMPANY_ID") REFERENCES "PUBLIC"."COMPANY"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."CLIENT_MISSION" ADD CONSTRAINT "PUBLIC"."FKNVAAN9SO9MBBP1H300SYAJ7FM" FOREIGN KEY("CLIENT_ID") REFERENCES "PUBLIC"."CLIENT"("ID") NOCHECK;              
